name: release
on:
  push:
    tags:
    - v*
    - "!latest*"
    - "!canary*"

# This configuration ensures that multiple releases don't run at the same time:
# - The 'group' combines the workflow name and git reference to create a unique identifier
# - 'cancel-in-progress: false' means if a new release is triggered, it will wait in line
#   instead of canceling any running release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: build
    uses: "./.github/workflows/build.yaml"
  release:
    name: release
    needs:
      - build
    runs-on: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "Publish release on GitHub"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          VERSION: ${{github.ref_name}}
        run: |
          go get -u github.com/tcnksm/ghr
          last_tag=$(git describe --tags ${VERSION}^ --abbrev=0 --always)
          ghr \
            -u cnabio \
            -r cnab-to-oci \
            -n "cnab-to-oci ${VERSION}" \
            -b "$(git log --no-merges --pretty=format:'- %s %H (%aN)' HEAD ^${last_tag})" \
            ${VERSION}